---
name: Andrew
surname: Allyn
position: "Senior Research Manager - Gulf of Maine Research Institute"
www: aallyn.github.io
email: "andrew.allyn@gmail.com"
github: aallyn

aboutme: |
  \RaggedRight About me text.

date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "6FA3CE" # my shirt on the profil pic is 839AC4, but we take a bit lighter for better look
urlcolor: blue
linkcolor: blue
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#######################
#### SHORT VERSION ####
#######################

# Whether to print a shortened version of the CV
short <- FALSE

########################
#### PACKAGE SETUP #####
########################

# Required packages
library(vitae)
library(dplyr)

# For Google scholar data/visualization
library(scholar)
library(ggplot2)
library(forcats)
library(patchwork)
library(see)
library(rsvg)
library(huxtable)
library(kableExtra)

# To format links throughout the CV
source("files/format_links.R")

########################
#### GOOGLE SCHOLAR ####
########################

# Specify your Google scholar profile
scholar.profile <- "-dn-gUsAAAAJ&hl" # Get it from your Google Scholar profile URL

# Specify your Google scholar short author name
author.name <- "a allyn"
# Note: correct name may vary (e.g., if you inconsistently used middle name initials)
# Dominique Makowski's was simply "d makowski", so the pattern is unclear 
# But usually it seems 1-3 letters from first name plus full last name

# When in doubt, the correct author name can be obtained through:
# source("files/get_scholar_name.R") # (after defining 'scholar.profile' above)

# Name inconsistencies should be corrected manually in file 'files/make_data_impact.R' (lines 14-16).

########################
##### INSTRUCTIONS #####
########################

# Change the order of sections below as desired.
# Edit the individual files ("childs") to edit the content as desired.
# Add `eval = !short` to code chunks to make them optional for the short version

```

```{r Education parent, child=c('sections/education.Rmd')}
```
```{r Research parent, child=c('sections/research.Rmd')}
```

```{r Publications parent, child=c('sections/publications.Rmd')}
```

```{r Grants parent, child=c('sections/grant.Rmd')}
```
<!-- 
```{r Awards parent, child=c('sections/awards.Rmd')}
```

```{r Other publications parent, child=c('sections/publications_other.Rmd'), eval = !short}
```

```{r Academic service parent, child=c('sections/service.Rmd'), eval = !short}
``` -->
