# Taken from: https://github.com/dmnemec/copy_file_to_another_repo_action
name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'cv.pdf'
        destination_repo: 'rempsyc/starter-academic'
        destination_folder: 'static'
        user_email: 'remi.theriault@mail.mcgill.ca'
        user_name: 'rempsyc'
        destination_branch: 'master'
        commit_message: 'update cv'